os: linux
dist: focal
language: python
addons:
  sbom:
    on:
      branch: sbom_one_fix
      pr: true
      condition: $OS = linux
    run_phase: before_script
    output_format: spdx-json
    output_dir: 'python'
  mariadb: '10.0'
script:
  - python hello_world.py
  - cd python
  - pip install -r requirements.txt
