os: linux
dist: focal
language: python
addons:
  sbom:
    on:
      branch: test1
      pr: true
      condition: $OS = linux
    run_phase: before_script
    output_format: spdx-json
    output_dir: 'python'
  mariadb: '10.0'
script:
  - echo test
