os: linux
dist: jammy
language: java
jdk:
  - openjdk8
jobs:
  include:
  - name: “test123” # existing functionality
    script: # existing functionality
      - java -version
  - name: “second 01” # existing functionality
    script: # existing functionality
      - java -version
